import { FlagsError } from '../errors/base.js';
import { parseFlagsJson } from '../sources/json/parse.js';
import { detectRuntime } from '../utils/runtime.js';
import type { FlagSpec, StringFlagSpec } from '../types/flag-spec.js';

interface CodegenOptions {
  readonly inPath: string;
  readonly outPath: string;
}

/**
 * Generate a typed `defineFlags<{...}>()` module from a `flags.json`
 * file. Preserves declared kinds, defaults, environments, value sets,
 * and rules — but skips runtime-only fields like `subjectId` and
 * `onEvaluation`.
 *
 * Output is intentionally formatted as plain TS with `as const` on
 * `string`-flag `values` so consumers retain literal-union narrowing.
 *
 * @param opts  Input path (`flags.json`) and output path (`*.ts`).
 *
 * @example
 *   await runCodegen({ inPath: 'flags.json', outPath: 'src/flags.gen.ts' });
 */
export async function runCodegen(opts: CodegenOptions): Promise<void> {
  const runtime = detectRuntime();
  if (runtime !== 'node' && runtime !== 'bun') {
    throw new FlagsError('INVALID_RUNTIME_OPTION', 'codegen requires Node.js or Bun');
  }
  const fs = await import('node:fs/promises');
  const raw = await fs.readFile(opts.inPath, { encoding: 'utf8' });
  const parsed = parseFlagsJson(raw);
  const lines: string[] = [
    '// Auto-generated by `flags codegen` — do not edit by hand.',
    "import { defineFlags } from '@devkit/flags';",
    '',
    'export const flags = defineFlags({',
    '  flags: {',
  ];
  for (const [key, spec] of Object.entries(parsed.flags)) {
    lines.push(`    ${JSON.stringify(key)}: ${stringifySpec(spec, '    ')},`);
  }
  lines.push('  },');
  if (Object.keys(parsed.segments).length > 0) {
    lines.push('  segments: {');
    for (const [name, group] of Object.entries(parsed.segments)) {
      lines.push(`    ${JSON.stringify(name)}: ${JSON.stringify(group)},`);
    }
    lines.push('  },');
  }
  lines.push('});');
  lines.push('');
  await fs.writeFile(opts.outPath, lines.join('\n'), { encoding: 'utf8' });
}

function stringifySpec(spec: FlagSpec, indent: string): string {
  if (spec.kind === 'string') {
    const stringSpec = spec as StringFlagSpec;
    if (stringSpec.values !== undefined) {
      const valuesLiteral = `[${stringSpec.values.map((v) => JSON.stringify(v)).join(', ')}] as const`;
      const rest = { ...spec } as Record<string, unknown>;
      delete rest['values'];
      return formatObject({ ...rest, values: `__VALUES__` }, indent).replace(
        '"__VALUES__"',
        valuesLiteral,
      );
    }
  }
  return formatObject(spec as unknown as Record<string, unknown>, indent);
}

function formatObject(obj: Record<string, unknown>, indent: string): string {
  const childIndent = `${indent}  `;
  const entries = Object.entries(obj);
  if (entries.length === 0) return '{}';
  const body = entries
    .map(([k, v]) => `${childIndent}${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
  return `{\n${body}\n${indent}}`;
}
